---
title: "Математична статистика. Лабораторна робота 2. Створення електронного документу в стилі грамотного програмування засобами R"
author: "Наталушко Д.О."
date: "`r Sys.Date()`"
output: 
  html_notebook:
    toc: true
    toc_float: true
    highlight: tango
fontsize: 12pt
header-includes:
  - \usepackage[T2A]{fontenc}
  - \usepackage[utf8]{inputenc}
  - \usepackage[russian]{babel}
editor_options:
  chunk_output_type: console
bibliography: references_lab.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Формула

$$
y(x) = b_0 + b_1x + b_2x^2
$$

$$
f(x) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\left( -\frac{(x - \mu)^2}{2\sigma^2} \right)
$$
## Задаємо параметри функції

```{r}
b0 <- 2
b1 <- 3
b2 <- 1.57
```

## Задаємо область визначення

```{r}
x <- seq(-1, 1, 0.1) 
y <- b0 + b1 * x + b2 * x^2
```

## Графік функції

```{r}
plot(x, y, type = "l", col = "red", 
     main = "Графік функції", 
     xlab = "x", ylab = "y")
points(x, y, col = "blue")
```

## Створюємо таблицю та зберігаємо її

```{r message=FALSE}
df <- data.frame(x = x, y = y)
library(rio)
if (!dir.exists("data")) dir.create("lab_2/data")
export(df, "lab_2/data/data.csv")

if (!requireNamespace("DT", quietly = TRUE)) install.packages("DT")
DT::datatable(df)
```

## Імпортуємо таблицю назад

```{r}
dfNew <- import("lab_2/data/data.csv")
knitr::kable(head(dfNew), caption = "*Табл. 1. Фрагмент таблиці даних*")
```

## Таблиця засобами stargazer

```{r}
if (!requireNamespace("stargazer", quietly = TRUE)) install.packages("stargazer")
stargazer::stargazer(head(dfNew),
 type = "html",
 summary = FALSE,
 title = "_Табл. 1. Фрагмент таблиці даних_")
```

## Таблиця засобами xtable

```{r}
if (!requireNamespace("xtable", quietly = TRUE)) install.packages("xtable")
print(xtable::xtable(head(dfNew),
 type = "html",
 html.table.attributes="border=0",
 summary = FALSE,
 caption = "_Табл. 1. Фрагмент таблиці даних_"))
```

```{r}
if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2")
library(ggplot2)
ggplot(df, aes(x = x, y = y)) +
  geom_line(color = "red", size = 1) +
  geom_point(color = "blue", size = 2) +
  labs(
    title = "Графік функції: y(x) = b₀ + b₁x + b₂x²",
    x = "x",
    y = "y"
  ) +
  theme_minimal(base_family = "Helvetica") +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```
```{r}
library(ggplot2)
library(magrittr)

df %>%
  ggplot(aes(x = x, y = y)) +
  geom_line(color = "red", size = 1) +
  geom_point(color = "blue", size = 2) +
  labs(
    title = "Графік функції: y(x) = b₀ + b₁x + b₂x²",
    x = "x",
    y = "y"
  ) +
  theme_minimal(base_family = "Helvetica") +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

```